install.packages("arrow")
library(arrow)
data <-read_parquet("PCV_Stacked.parquet")
head(data)
ncol(data)
nrow(data)  
names(data)
str(data)
unique(data$product_name)
unique(data$sub_product_name)
unique(data$manufacture_site)
unique(data$variant)
length(unique(data$batch_number))
length(unique(data$parameter))
summary(data$weighted_avg_value)
summary(table(data$batch_number))
table(data$product_name, data$variant)
save(data, file = "data.RData")

